import type { Metadata } from "next";

import "./globals.css";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";

const GAId = process.env.NEXT_PUBLIC_GA_ID || "";
const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID || "";

export const metadata: Metadata = {
  title: "buildnow",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/image/logo_symbolOnly.ico",
        href: "/image/logo_symbolOnly.ico",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/image/logo_symbolOnly_dark.ico",
        href: "/image/logo_symbolOnly_dark.ico",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head></head>
      <body>{children}</body>
      <GoogleAnalytics gaId={GAId} />
      <GoogleTagManager gtmId={GTM_ID} />
    </html>
  );
}
