import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "buildnow",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/image/logo_symbolOnly.ico",
        href: "/image/logo_symbolOnly.ico",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/image/logo_symbolOnly_dark.ico",
        href: "/image/logo_symbolOnly_dark.ico",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
